### ISSUE TITLE
error when reproducing the results

### ISSUE THREAD

**Issue by juliecious** [rehmanzafar/dlime_experiments#2]
Thank you for the great paper. 

When I was running the code in `experiments_bc_rf.py`, I got an error in [line 80](https://github.com/rehmanzafar/dlime_experiments/blob/beb6860c6858dfe0bb83a5d80eb79de870794cab/experiments_bc_rf.py#L80)

This method `as_pyplot_to_figure` belongs to Explanation object but not to `explainer_tabular. LimeTabularExplainer`. It seems to me that these two objects are independent from each other. Have I missed anything? Could you please advise how to reproduce the result correctly?

Here is the [Colab](https://colab.research.google.com/drive/1i0qv-9SuqRQh5t1TQyEGElRJFYLeQ4gy?usp=sharing) I used.

**Comment by rehmanzafar** [comment]
Hi Juliecious,

Thank you for your interest in our work.

This script is saving charts in results folder which is missing in dlime_experiments folder.  Just create results folder inside the dlime_experiments by executing the following command to fix the error:
`
cd dlime_experiments/
`
`
mkdir results
`

Regards,
Rehman
